// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPC() {
  return window['go']['main']['App']['GetPC']();
}

export function GetTaskActiveItemSingle(arg1) {
  return window['go']['main']['App']['GetTaskActiveItemSingle'](arg1);
}

export function GetTaskItems(arg1) {
  return window['go']['main']['App']['GetTaskItems'](arg1);
}

export function GetTaskSingle(arg1) {
  return window['go']['main']['App']['GetTaskSingle'](arg1);
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}
