// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetPC():Promise<any>;

export function GetTasks(arg1:number):Promise<Array<main.Task>>;
